plugins {
    id 'com.android.application'
}

android {
    namespace 'com.modserver.stats.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.modserver.stats.app'
        minSdk 23
        targetSdk 35
        versionCode 13
        versionName '1.12'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
